apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-ssh-vm
  annotations:
    description: VM as code example
  labels:
    app: fedora-ssh-vm
    os.template.kubevirt.io/fedora: 'true'
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: fedora-ssh-vm
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: q35
        memory:
          guest: 2Gi
      hostname: fedora-ssh-vm
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora
              chpasswd: { expire: False }
          name: cloudinitdisk
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: authorised-keys
---
apiVersion: v1
kind: Secret
metadata:
  name: authorised-keys
data:
  key: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FDMlNxcGZQNnQvbXdmSFFhUGFCeGp0R2JaaGptR0EvME1yUnJWY3owQjREVGErYXVVemhjeFNPQTBMeFRsQ29HRUM5S1Y3M3MyZ0N6WS9zOEo2SUlpd0FsY3BqbVdGYzlCWU5FdlB6NEFkQUlCVGhTS29rRTRCUnV4aUhFdDFEMU1HL2tjUXpwR05FQkxmL0c3TkkvaUVGVjE3UzFYYktaNS9uRitZdDFHYzBSRUlVQmlzOWxzTEM0NmlZaFJBbEFGMFVySkJNQmYvRlBaRWhLRjh3c1RGSUQ3czh1cDVwTDM1M0JhL1MxWTYvYVdRKzk3YXNrR3dydlppMjdKRXcwR0JQajE4dytFSWRCZVpwZ0VuS0tUMUVmc0l3TWpkZzgrUDloK012RnJaU2xyellxNEphNWhFcm5ZbHlidGszcXc5d1MyM1krU0V1SXoxYk53MEZxalhJN3lwaG9aZ204UWJzaWdrbnQxUGZralVnUXZBN2YyMHd3Ukd1U29uTm8yc3FoWTRWRCtFc09sTVdxdGZYQ3czVFFIWWpWb1pRWktiMnAxdXZLUnY3SXBoRFMzUmhsYkpmZkJSMERtV0pLZEZLT29FaXVZRCtsK1MyaGtkaEdmZitSVDcxUGtEaFhNWXpsWHpDQnQyUFExZ0JVS3dhVGR2dlIzYW9FZE05NnM9IHVzZXJAd29ya3NwYWNlMmM2NDEwNWQ4YTZkNDEzZi01Y2NiYmY0YzY3LTVqaGRoCg==
