---
apiVersion: velero.io/v1
kind: Backup
metadata:
  # Change this to the desired backup name
  name: backup-fedora02
  namespace: oadp-user1
  labels:
    velero.io/storage-location: default
spec:
  defaultVolumesToFsBackup: false
  orLabelSelectors:
  - matchLabels:
      # Change this to the desired VM
      app: fedora02
  - matchLabels:
      # Change this to the desired VM
      vm.kubevirt.io/name: fedora02
  csiSnapshotTimeout: 10m0s
  ttl: 720h0m0s
  itemOperationTimeout: 4h0m0s
  storageLocation: oadp-dpa-1
  hooks: {}
  includedNamespaces:
  # Change this to the desirted namespace
  - vmexamples-user2
  snapshotMoveData: false